default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/tasks-dev.sqlite3

production:
  <<: *default
  database: db/tasks-prod.db

test:
  <<: *default
  database: db/tasks-test.sqlite3
